export const Int32Array: any;
export const SharedArrayBuffer: any;
export const Worker: any;
export const addEventListener: any;
export const postMessage: any;
export const ignore: any;
export const isArray: (arg: any) => arg is any[];
export const notify: any;
export const wait: any;
export const waitAsync: any;
